laci_indiana.settings:
  type: config_object
  label: 'LACI Indiana settings'
  mapping:
    ic_year:
      type: string
      label: 'Indiana Code year'
    enabled_authority_types:
      type: sequence
      label: 'Enabled authority type term IDs'
      sequence:
        type: integer
        label: 'Term ID'
